### PR TITLE
fixing build issue for VS2013

### PR DESCRIPTION
**Pull request by mikehancock**
it seems that VS2015 uses a version of Newtonsoft.Json that doesn't work in VS2013. Not sure why but updating usung VS2013 works in both version of VS.

Have also excluded all the packages from git, shouldn't really be stored there, should restore on build.

### CODE REVIEW

**Comment by mikehancock** [comment]
@LukeFieldsend @daningrey please can you review this

**Comment by daningrey** [comment]
:+1:

**Comment by LukeFieldsend** [comment]
Does this version of newtonsoft use a different pcl profile? I'm just worried it may cause problems for the Xamarin SDK using it. can you send me the built dll and I'll drop it in my test build

**Comment by mikehancock** [comment]
@LukeFieldsend the profile on master is portable45-net45+win8+wp8+wpa81 - so if you are using the current version on Nuget then it should work fine

**Comment by LukeFieldsend** [comment]
:+1:

**Pull request merged**
